trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    shopt -s extglob dotglob
    mkdir helics
    mv !(helics) helics
    shopt -u dotglob
  displayName: 'Move helics-ns3 module files into subfolder'

- script: |
    sudo apt-get install -y  libzmq5-dev ninja-build
  displayName: 'Apt install required Boost and ZeroMQ libraries'

- script: |
    cmake --version
    git clone https://github.com/GMLC-TDC/HELICS-src
    cd HELICS-src
    git checkout develop
    mkdir build
    cd build
    cmake -GNinja ../ -DBUILD_HELICS_TESTS=OFF -DBUILD_HELICS_EXAMPLES=OFF
    ninja
    sudo ninja install
  displayName: 'Install HELICS'

- script: git clone https://gitlab.com/nsnam/ns-3-dev.git
  displayName: 'Clone latest ns-3'

- script: |
    mv helics ns-3-dev/contrib
    cd ns-3-dev
    ./waf configure --disable-werror --with-helics=/usr/local --enable-modules=helics --enable-examples --enable-tests | tee azure_waf_configure.log
    ! grep -Fq "HELICS not enabled" azure_waf_configure.log
  displayName: 'Configure ns-3'

- script: |
    cd ns-3-dev
    ./waf build
  displayName: 'Build ns-3'
